<?php

declare(strict_types=1);

namespace Storm\AggregateRepository\Snapshot;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Exception;
use Doctrine\DBAL\ParameterType;
use JsonException;
use Storm\Clock\Exception\InvalidDateTimeException;
use Storm\Clock\PointInTime;
use Storm\Support\Dbal\BatchedDelete;
use Symfony\Component\DependencyInjection\Attribute\AsAlias;

/**
 * DBAL `SnapshotStore` on the `snapshots` table: latest-only via `INSERT … ON CONFLICT (stream) DO
 * UPDATE`, one row per stream moved forward on each save; `save()` enforces the monotonic guard in SQL.
 */
#[AsAlias(SnapshotStore::class)]
final readonly class DbalSnapshotStore implements SnapshotStore
{
    public function __construct(
        private Connection $connection,
    ) {}

    /**
     * {@inheritDoc}
     *
     * Returns null also when the stored snapshot is unreadable OR semantically unusable: invalid-JSON
     * state, an unparseable created_at, a decoded state that is not an associative bag, or a
     * non-positive version. Jsonb happily stores a scalar or a list; fed to `Snapshot(array $state)` a
     * scalar would escape as a raw TypeError, and the writer only ever snapshots at version >= 1. A
     * snapshot is only a cache; events stay authoritative and the caller already falls back to a full
     * reconstitution on null, so a corrupt entry is not an error to surface; the same doctrine covers
     * the whole row, not only its JSON syntax.
     *
     * A corrupt row is DELETED on sight, not merely skipped: a silent skip would full-replay on every
     * read forever, because `save()`'s monotonic guard refuses to overwrite at the same version, the
     * one repair a corrupt-at-current-version row needs. Deleting makes the next save at ANY version
     * regenerate the cache; until then reads replay from the authoritative events, which null already
     * means.
     *
     * @infection-ignore-all This method is integration-by-nature: what it asserts is that a real SELECT
     * maps onto a Snapshot, and only a real Postgres can prove it; the integration DbalSnapshotStoreTest
     * covers hit, miss, upsert, no-regress, and delete. The corruption arm is the one exception,
     * unreachable through the jsonb/timestamptz schema, so it is unit-tested against a mocked row, and
     * that single unit test is enough to drag the whole method into the mutation field, where every
     * mutant on the SELECT, the column casts or the `$row === false` miss survives by construction: the
     * unit-only scope never runs the integration suite that kills them. Killing them here would mean
     * asserting SQL through a mocked Connection, the over-mocking this repo refuses. Ignored rather than
     * faked, so the gate keeps meaning "behavior unit tests can honestly own".
     *
     * @throws Exception on a DBAL failure
     */
    public function load(string $stream): ?Snapshot
    {
        $row = $this->connection->fetchAssociative(
            /** @lang PostgreSQL */
            'SELECT stream, aggregate_type, version, state, created_at FROM snapshots WHERE stream = :stream',
            ['stream' => $stream],
        );

        if ($row === false) {
            return null;
        }

        try {
            $state = json_decode((string) $row['state'], true, 512, JSON_THROW_ON_ERROR);
            $version = (int) $row['version'];

            // jsonb accepts any JSON value, but a snapshot state is an associative bag and its version
            // is >= 1 by the writer's construction; anything else is a corrupt cache row: a miss, the
            // same doctrine as the JSON catch below, never a TypeError escaping the port.
            if ($version < 1 || ! is_array($state) || ($state !== [] && array_is_list($state))) {
                return $this->discard($stream);
            }

            /** @var array<string, mixed> $state */
            return new Snapshot(
                (string) $row['stream'],
                (string) $row['aggregate_type'],
                $version,
                $state,
                PointInTime::fromStorage((string) $row['created_at']),
            );
        } catch (JsonException|InvalidDateTimeException) {
            return $this->discard($stream); // corrupt cache entry deleted, then full replay, regenerated by the next save
        }
    }

    /**
     * A corrupt row is removed, not skipped, and the read stays a miss: see `load()`; the monotonic
     * `save()` could never repair it at the same version, so deletion is what makes the cache
     * self-healing for real. The delete is BEST-EFFORT: a read must stay a read where writes are
     * impossible, so on a read-only replica or inside a read-only transaction the failed delete
     * still degrades to a miss instead of hardening a corrupt CACHE row into a read failure; the
     * healing simply waits for a writable context.
     */
    private function discard(string $stream): null
    {
        try {
            $this->connection->executeStatement(
                /** @lang PostgreSQL */
                'DELETE FROM snapshots WHERE stream = :stream',
                ['stream' => $stream],
            );
        } catch (Exception) {
            // swallowed by design, see above
        }

        return null;
    }

    /**
     * {@inheritDoc}
     *
     * Monotonicity is enforced in SQL: the `ON CONFLICT` guard `WHERE EXCLUDED.version >
     * snapshots.version` only moves the row forward, so a stale save is a silent no-op. The sweep reads
     * the head, reconstitutes, then saves without a single transaction, so two overlapping sweeps can
     * race; without the guard the one finishing last would overwrite a newer snapshot with older state.
     * That would not corrupt anything, since events stay authoritative, but the guard is free and mirrors
     * the compare-and-set the event store enforces.
     *
     * @throws JsonException when the snapshot state cannot be encoded to JSON
     * @throws Exception on a DBAL failure
     */
    public function save(Snapshot $snapshot): void
    {
        $this->connection->executeStatement(
            /** @lang PostgreSQL */
            <<<'SQL'
                INSERT INTO snapshots (stream, aggregate_type, version, state, created_at)
                VALUES (:stream, :aggregate_type, :version, CAST(:state AS jsonb), :created_at)
                ON CONFLICT (stream) DO UPDATE SET
                    aggregate_type = EXCLUDED.aggregate_type,
                    version        = EXCLUDED.version,
                    state          = EXCLUDED.state,
                    created_at     = EXCLUDED.created_at
                WHERE EXCLUDED.version > snapshots.version
                SQL,
            [
                'stream' => $snapshot->stream,
                'aggregate_type' => $snapshot->aggregateType,
                'version' => $snapshot->version,
                'state' => json_encode($snapshot->state, JSON_THROW_ON_ERROR),
                'created_at' => $snapshot->createdAt->toString(),
            ],
        );
    }

    /**
     * {@inheritDoc}
     *
     * @throws Exception on a DBAL failure
     */
    public function delete(string $stream): bool
    {
        return $this->connection->executeStatement(
            /** @lang PostgreSQL */
            'DELETE FROM snapshots WHERE stream = :stream',
            ['stream' => $stream],
        ) > 0;
    }

    /**
     * {@inheritDoc}
     *
     * @throws Exception on a DBAL failure
     */
    public function staleStreams(string $category, int $threshold, ?int $maxAge, ?int $minInterval, int $batch, ?string $after = null): array
    {
        // The category filter is a KEY RANGE on the primary key, not an expression: streams of one
        // category are the exact prefix range [category-, category.), `.` being the successor byte
        // of `-`, so the planner walks one contiguous index slice, first page included; a
        // `split_part()` predicate would scan every row sorting before the category on each fresh
        // sweep. The lower bound also seeds the cursor, and a bare category stream, which carries
        // no qualifier to rebuild an identity from, falls outside the range on purpose.
        //
        // Reading that bound in BYTES is exactly what `stream_heads.stream COLLATE "C"` buys. Under a
        // libc locale collation punctuation weighs less than letters, so `category.` sorts BELOW every
        // stream of the category and this returns nothing, with no error to show for it.
        return $this->connection->fetchFirstColumn(
            /** @lang PostgreSQL */
            <<<'SQL'
                SELECT h.stream
                FROM stream_heads h
                LEFT JOIN snapshots s ON s.stream = h.stream
                WHERE h.stream > :cursor
                  AND h.stream < :upper
                  AND (
                        ( h.last_version - COALESCE(s.version, 0) >= :threshold
                          AND ( s.created_at IS NULL
                                OR CAST(:min_interval AS int) IS NULL
                                OR s.created_at < now() - (CAST(:min_interval AS int) * interval '1 second') ) )
                     OR ( CAST(:max_age AS int) IS NOT NULL
                          AND h.last_version - COALESCE(s.version, 0) >= 1
                          AND s.created_at < now() - (CAST(:max_age AS int) * interval '1 second') )
                      )
                ORDER BY h.stream
                LIMIT :batch
                SQL,
            ['cursor' => $after ?? $category.'-', 'upper' => $category.'.', 'threshold' => $threshold, 'max_age' => $maxAge, 'min_interval' => $minInterval, 'batch' => $batch],
            ['threshold' => ParameterType::INTEGER, 'max_age' => ParameterType::INTEGER, 'min_interval' => ParameterType::INTEGER, 'batch' => ParameterType::INTEGER],
        );
    }

    /**
     * {@inheritDoc}
     *
     * @throws Exception on a DBAL failure
     */
    public function countOrphans(): int
    {
        return (int) $this->connection->fetchOne(
            /** @lang PostgreSQL */
            'SELECT count(*) FROM snapshots s WHERE NOT EXISTS (SELECT 1 FROM stream_heads h WHERE h.stream = s.stream)',
        );
    }

    /**
     * {@inheritDoc}
     *
     * @throws Exception on a DBAL failure
     */
    public function pruneOrphans(int $batch): int
    {
        // The predicate runs against `snapshots` unaliased in BatchedDelete's inner select, so the
        // anti-join qualifies by the table name, not an alias.
        return BatchedDelete::run(
            $this->connection,
            'snapshots',
            'NOT EXISTS (SELECT 1 FROM stream_heads h WHERE h.stream = snapshots.stream)',
            [],
            $batch,
        );
    }
}
